<!DOCTYPE html><html lang="en" class="h-full bg-slate-25 type-d-100"><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><link rel="preload" as="image" href="/build/assets/limewire-logo-CWTx4rdZ.svg"/><link rel="preload" as="image" href="/build/assets/limewire-icon-CuSTCjU4.svg"/><script src="https://jsc.mgid.com/site/1110887.js" async=""></script><meta name="theme-color" content="#00934b"/><title>Download CyberNetwork.tsx | LimeWire</title><meta name="description" content="Download CyberNetwork.tsx on LimeWire"/><meta property="twitter:title" content="Download CyberNetwork.tsx | LimeWire"/><meta property="twitter:description" content="Download CyberNetwork.tsx on LimeWire"/><meta property="twitter:image" content="https://limewire.com/img/remix/twitter_card_image_file_sharing.png"/><meta property="twitter:card" content="summary_large_image"/><meta property="twitter:site" content="@limewire"/><meta property="twitter:creator" content="@limewire"/><meta property="og:title" content="Download CyberNetwork.tsx | LimeWire"/><meta property="og:description" content="Download CyberNetwork.tsx on LimeWire"/><meta property="og:image" content="https://limewire.com/img/remix/twitter_card_image_file_sharing.png"/><meta property="og:type" content="website"/><meta property="og:site_name" content="LimeWire"/><link rel="apple-touch-icon" href="/apple-touch-icon.png" type="image/png" sizes="180x180"/><link rel="icon" href="/favicon-32x32.ico" sizes="32x32"/><link rel="modulepreload" href="/build/chunks/entry/entry.client-h-8J_f_U.js"/><link rel="modulepreload" href="/build/chunks/jsx-runtime-D_zvdyIk.js"/><link rel="modulepreload" href="/build/chunks/chunk-4N6VE7H7-CYH4PXiQ.js"/><link rel="modulepreload" href="/build/chunks/tooltip-Dh-GCyoz.js"/><link rel="modulepreload" href="/build/chunks/correctAssetUrl-8jt7Bzg0.js"/><link rel="modulepreload" href="/build/chunks/file-sharing-provider-NtsXpuMT.js"/><link rel="modulepreload" href="/build/chunks/sentry-DCGaZcF5.js"/><link rel="modulepreload" href="/build/chunks/button-CB2fQLpx.js"/><link rel="modulepreload" href="/build/chunks/index-5zs3RZdd.js"/><link rel="modulepreload" href="/build/chunks/env-context-DebTkedx.js"/><link rel="modulepreload" href="/build/chunks/form-validation-BmVkRcjs.js"/><link rel="modulepreload" href="/build/chunks/StripeModal-D_zJSTg3.js"/><link rel="modulepreload" href="/build/chunks/error-CNFYeXfL.js"/><link rel="modulepreload" href="/build/chunks/forward-platform-action-cZbimJfK.js"/><link rel="modulepreload" href="/build/chunks/runtime-a9fv597q.js"/><link rel="modulepreload" href="/build/chunks/toggle-group-BSQQLJtK.js"/><link rel="modulepreload" href="/build/chunks/focus-visible-outline-CA5WDHp1.js"/><link rel="modulepreload" href="/build/chunks/footer-BhUrYW9s.js"/><link rel="modulepreload" href="/build/chunks/link-button-Dgv_yPAf.js"/><link rel="modulepreload" href="/build/chunks/plus-icon-BzkK1_R0.js"/><link rel="modulepreload" href="/build/chunks/arrow-right-icon-CJx94PN2.js"/><link rel="modulepreload" href="/build/chunks/navigation-tabs-BJf4kUpl.js"/><link rel="modulepreload" href="/build/chunks/use-callback-ref-CJ9SODNh.js"/><link rel="modulepreload" href="/build/chunks/alert-Bsob527P.js"/><link rel="modulepreload" href="/build/chunks/base-button-BOVQiXV3.js"/><link rel="modulepreload" href="/build/chunks/use-state-ref-0aYGV7fB.js"/><link rel="modulepreload" href="/build/chunks/result-BtcenhOc.js"/><link rel="modulepreload" href="/build/chunks/gtm-CBAuTBQe.js"/><link rel="modulepreload" href="/build/chunks/get-api-DWzc_bBF.js"/><link rel="modulepreload" href="/build/chunks/use-controlled-state-6BKWRsRt.js"/><link rel="modulepreload" href="/build/chunks/resolve-to-node-Bl44lgnH.js"/><link rel="modulepreload" href="/build/chunks/runtime-2_b2CLRu.js"/><link rel="modulepreload" href="/build/chunks/VerificationStatusEnum-BMWjV5ER.js"/><link rel="modulepreload" href="/build/chunks/AccountSubscriptionTier-Cz37hh3K.js"/><link rel="modulepreload" href="/build/chunks/UsStateCodeAlpha2-sRkxuwjy.js"/><link rel="modulepreload" href="/build/chunks/form-schema-utils-CKHKKg7G.js"/><link rel="modulepreload" href="/build/chunks/types-CeqL-daw.js"/><link rel="modulepreload" href="/build/chunks/modal-content-window-title-header-DByhHMtf.js"/><link rel="modulepreload" href="/build/chunks/noop-BjFrJKj1.js"/><link rel="modulepreload" href="/build/chunks/preload-helper-ckwbz45p.js"/><link rel="modulepreload" href="/build/chunks/create-lazy-singleton-cLopSc4o.js"/><link rel="modulepreload" href="/build/chunks/use-self-cancel-timeout-DCHuMrr-.js"/><link rel="modulepreload" href="/build/chunks/use-self-cancel-interval-BgB7hfvd.js"/><link rel="modulepreload" href="/build/chunks/createFormData-6W1bV2BK.js"/><link rel="modulepreload" href="/build/chunks/get-sharing-bucket-expiration-label-BxASTJP2.js"/><link rel="modulepreload" href="/build/chunks/auth-form-BNw1-pAv.js"/><link rel="modulepreload" href="/build/chunks/use-typed-explicit-fetcher-fhEyK6eX.js"/><link rel="modulepreload" href="/build/chunks/authenticity-token-CFgl6Z4h.js"/><link rel="modulepreload" href="/build/chunks/auth-form-validation-C7l7Lp9m.js"/><link rel="modulepreload" href="/build/chunks/use-const-CyuDI2Jw.js"/><link rel="modulepreload" href="/build/chunks/auth-context-DVtKf2vI.js"/><link rel="modulepreload" href="/build/chunks/navigation-link-De5ItD8a.js"/><link rel="modulepreload" href="/build/chunks/app-integration-provider-4-SaOz_c.js"/><link rel="modulepreload" href="/build/chunks/app-integration-loading-D3uWt4C6.js"/><link rel="modulepreload" href="/build/chunks/client-only-CnbT09nL.js"/><link rel="modulepreload" href="/build/chunks/auth-window-messenger-DvswJzyt.js"/><link rel="modulepreload" href="/build/chunks/use-external-wallet-dcgxeJzM.js"/><link rel="modulepreload" href="/build/chunks/divider-Bx5FVaq5.js"/><link rel="modulepreload" href="/build/chunks/user-context-H9i7VnPA.js"/><link rel="modulepreload" href="/build/chunks/CryptoCurrency-C8i-2yC7.js"/><link rel="modulepreload" href="/build/chunks/format-crypto-currency-DU9teVm2.js"/><link rel="modulepreload" href="/build/chunks/index-CWrIKnBx.js"/><link rel="modulepreload" href="/build/chunks/file-name-D6aW1GMb.js"/><link rel="modulepreload" href="/build/chunks/content-item-name-BgJnKYk_.js"/><link rel="modulepreload" href="/build/chunks/feedback-tooltip-DnQoTtgx.js"/><link rel="modulepreload" href="/build/chunks/dropdown-menu-item-Db0oH43Q.js"/><link rel="modulepreload" href="/build/chunks/CompositeItem-C2QJYDDY.js"/><link rel="modulepreload" href="/build/chunks/file-descriptor-CGrQeZua.js"/><link rel="modulepreload" href="/build/chunks/format-1NPDPTzm.js"/><link rel="modulepreload" href="/build/chunks/shared-DwIwScEe.js"/><link rel="modulepreload" href="/build/chunks/use-copyright-Dc7D5n5M.js"/><link rel="modulepreload" href="/build/chunks/tab-button-Ds5-Xr2w.js"/><link rel="modulepreload" href="/build/chunks/entry/root-Y8iUtRpO.js"/><link rel="modulepreload" href="/build/chunks/use-sentry-capture-route-error-DQjqgE2j.js"/><link rel="modulepreload" href="/build/chunks/root-data-from-meta-_uWRppwb.js"/><link rel="modulepreload" href="/build/chunks/mgid-BClyNFEN.js"/><link rel="modulepreload" href="/build/chunks/page-error-content-beLpRn94.js"/><link rel="modulepreload" href="/build/chunks/default-shell-layout-GstI-jbb.js"/><link rel="modulepreload" href="/build/chunks/api-context-7msjQt-g.js"/><link rel="modulepreload" href="/build/chunks/creator-name-CiLx5-S8.js"/><link rel="modulepreload" href="/build/chunks/asset-aspect-ratio-CFxZTYNK.js"/><link rel="modulepreload" href="/build/chunks/limewire-logo-Dqzw9EF0.js"/><link rel="modulepreload" href="/build/chunks/use-logout-DTFjcmcZ.js"/><link rel="modulepreload" href="/build/chunks/creator-834ASwQB.js"/><link rel="modulepreload" href="/build/chunks/errors-Bt-IsbGS.js"/><link rel="modulepreload" href="/build/chunks/entry/__root-4OwC_upI.js"/><link rel="modulepreload" href="/build/chunks/mgid-slot-DhBerfc6.js"/><link rel="modulepreload" href="/build/chunks/share-nearby-provider-CwuMIupI.js"/><link rel="modulepreload" href="/build/chunks/script-EPnTUGRP.js"/><link rel="modulepreload" href="/build/chunks/copy-input-0I8Jahig.js"/><link rel="modulepreload" href="/build/chunks/entry/_id-C1I2UVlI.js"/><link rel="modulepreload" href="/build/chunks/shell-layout-aside-65Zf2JuP.js"/><link rel="modulepreload" href="/build/chunks/page-column-layout-DWZQyDxP.js"/><link rel="modulepreload" href="/build/chunks/get-default-seo-preview-image-19rrZO0W.js"/><link rel="modulepreload" href="/build/chunks/page-error-404-Ba3LfCNG.js"/><link rel="modulepreload" href="/build/chunks/date-time-D44bRngG.js"/><link rel="stylesheet" href="/build/assets/nprogress-Dw03ZESa.css"/><link rel="stylesheet" href="/build/assets/react-datepicker-CE21K4bl.css"/><link rel="stylesheet" href="/build/assets/400-C8LWbix3.css"/><link rel="stylesheet" href="/build/assets/500-B36wLJV3.css"/><link rel="stylesheet" href="/build/assets/700-C5Ia9mPP.css"/><link rel="stylesheet" href="/build/assets/tailwind-C1kcPAQu.css"/></head><body class="h-full"><noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TZPQT7Z8" height="0" width="0" style="display:none;visibility:hidden" title="Google Tag Manager"></iframe></noscript><div style="--lmwr-banner-height:0px;--lmwr-navigation-height:3.5rem;--lmwr-navigation-sticky-height:calc(var(--lmwr-navigation-height) * var(--lmwr-navigation-non-sticky-height-percent, 1))" class="min-h-full grid grid-cols-1 grid-rows-[auto_auto_minmax(0,_1fr)]"><div class="z-50"></div><div class="h-[--lmwr-navigation-height] z-40 sticky top-0"><nav class="h-full bg-slate-25 after:content-empty after:absolute after:w-full after:h-px after:bg-slate-200 after:bottom-0"><div class="flex items-center gap-x-3 h-full min-w-0 px-3.5 md:px-4"><div class="flex items-center h-full min-w-0 flex-none"><a class="hidden md:flex h-10 outline-offset-0 flex-none items-center rounded-sm" href="/" data-discover="true"><img class="w-32 object-contain" src="/build/assets/limewire-logo-CWTx4rdZ.svg" alt="LimeWire Logo"/></a><a class="flex md:hidden h-10 outline-offset-0 flex-none items-center rounded-sm" href="/" data-discover="true"><img class="w-8 object-contain" src="/build/assets/limewire-icon-CuSTCjU4.svg" alt="LimeWire Logo"/></a></div><div class="h-6 flex items-center min-w-0"><div class="lg:flex-none flex-1 min-w-0 h-full flex items-center border-l-slate-300 border-l pl-3"><button type="button" tabindex="0" data-base-ui-click-trigger="" id="base-ui-_R_qqiaral5_" aria-haspopup="dialog" aria-expanded="false" class="default:rounded-sm block h-10 text-slate-900 min-w-0 w-full"><span class="flex flex-row items-center gap-x-2 min-w-0"><span style="mask-image:url(/build/assets/sharing-bucket-single-file-icon-CoFWt95U.svg);-webkit-mask-image:url(/build/assets/sharing-bucket-single-file-icon-CoFWt95U.svg)" class="default:block default:flex-none default:bg-current mask-center mask-contain mask-no-repeat w-4 h-4 text-slate-700 flex-none hidden lg:block"></span><span class="min-w-0 max-w-64 flex-1"><span class="default:type-d-50 default:text-slate-900 default:overflow-hidden flex flex-row items-center flex-nowrap min-w-0 type-d-100-medium"><span class="overflow-hidden text-ellipsis whitespace-nowrap">CyberNetwork</span><span class="flex-none whitespace-nowrap">.tsx</span></span></span><span style="mask-image:url(/build/assets/chevron-down-icon-gfhbPJjL.svg);-webkit-mask-image:url(/build/assets/chevron-down-icon-gfhbPJjL.svg)" class="default:block default:flex-none default:bg-current mask-center mask-contain mask-no-repeat w-4 h-4 transition-transform"></span></span></button></div><div class="h-full max-w-56 flex items-center flex-none type-d-75 text-slate-500 border-l-slate-300 border-l ml-3 pl-3"><div class="text-nowrap overflow-hidden text-ellipsis min-w-0">20.3KB</div></div><div class="h-full lg:flex-1 hidden lg:flex items-center min-w-0 flex-wrap overflow-hidden"><div class="h-full"></div><div class="h-full max-w-56 flex items-center flex-none type-d-75 text-slate-500 border-l-slate-300 border-l ml-3 pl-3"><div class="text-nowrap overflow-hidden text-ellipsis min-w-0"><span class="bg-slate-300 h-5 rounded-md block w-28"></span></div></div><div class="h-full max-w-56 flex items-center flex-none type-d-75 text-slate-500 border-l-slate-300 border-l ml-3 pl-3"><div class="text-nowrap overflow-hidden text-ellipsis min-w-0"><span class="bg-slate-300 h-5 rounded-md block w-24"></span></div></div></div></div><div class="flex items-center h-full flex-none min-w-0 ml-auto gap-x-2"><div><div class="md:hidden w-10 h-10 bg-slate-300 rounded-full"></div><div class="hidden md:flex w-32 h-10 bg-slate-300 rounded-full"></div></div><div class="items-center flex-none gap-x-2 hidden sm:flex"><div><div class="lg:hidden w-10 h-10 bg-slate-300 rounded-full"></div><div class="hidden lg:flex w-28 h-10 bg-slate-300 rounded-full"></div></div><div class="w-10 h-10 bg-slate-300 rounded-full"></div><div class="w-10 h-10 bg-slate-300 rounded-full"></div></div></div></div></nav></div><div><div class="default:min-h-full grid"><div class="w-full h-full grid grid-cols-1 grid-rows-1 md:grid-cols-[minmax(0,1fr)]"><main class="w-full min-h-full"><div class="h-full w-full flex items-center justify-center"><span class="default:w-5 default:h-5 default:border-2 animate-spin block border-t-current border-r-current border-solid border-b-transparent border-l-transparent rounded-full w-7 h-7"></span></div></main></div></div></div></div><div class="lg:hidden fixed top-0 left-0 overflow-hidden pointer-events-none -z-50"></div><script>
function __removeSearchParam() {
  try {
    var url = new URL(window.location.href);
    if (url.searchParams.has("lmwr-ftv")) {
      url.searchParams.delete("lmwr-ftv");
      window.history.replaceState(null, "", url.href);
    } 
  } catch (e) {}
}
__removeSearchParam();
</script><script>window.ENV = {"NOW":"2026-09-25T01:44:23.554Z","CLIENT_BASE_URL":"https://limewire.com","IS_DEV":false,"IS_STAGING":false,"API_BASE_URL":"https://api.limewire.com","CANONICAL_BASE_URL":"https://limewire.com","LIMEWIRE_FREE_USER_ID":"7f219511-0a09-403c-a94b-caa56419b5f8","LIMEWIRE_PRO_USER_ID":"1e2c66a9-7073-499b-86fb-b134a088ce44","SENTRY_DSN":"https://3914d239cc544007a8bc3b33c2e276e7:375389f9b8fc4a58aac7ddf053335cd6@o4505008135340032.ingest.sentry.io/4505114707099648","SENTRY_ENVIRONMENT":"production","SENTRY_PROJECT":"limewire-js-remix","GIT_RELEASE":"f85f0ca344014a7d746fa6a78746a729ef7e2e8f","STORYBLOCK_SPACE_ACCESS_TOKEN":"jmGRmWycHD5MvliLQXFkXAtt","TURNSTILE_SITEKEY":"0x4AAAAAAEVmA3xwky6ar3WJ"}</script><script>window.__reactRouterContext = {"basename":"/","future":{"unstable_optimizeDeps":false,"v8_passThroughRequests":false,"unstable_trailingSlashAwareDataRequests":false,"unstable_previewServerPrerendering":false,"v8_middleware":false,"v8_splitRouteModules":false,"v8_viteEnvironmentApi":false},"routeDiscovery":{"mode":"lazy","manifestPath":"/__manifest"},"ssr":true,"isSpaMode":false};window.__reactRouterContext.stream = new ReadableStream({start(controller){window.__reactRouterContext.streamController = controller;}}).pipeThrough(new TextEncoderStream());</script><script type="module" async="">;
import * as route0 from "/build/chunks/entry/root-Y8iUtRpO.js";
import * as route1 from "/build/chunks/entry/__root-4OwC_upI.js";
import * as route2 from "/build/chunks/entry/_id-C1I2UVlI.js";
  window.__reactRouterManifest = {
  "entry": {
    "module": "/build/chunks/entry/entry.client-h-8J_f_U.js",
    "imports": [
      "/build/chunks/jsx-runtime-D_zvdyIk.js",
      "/build/chunks/chunk-4N6VE7H7-CYH4PXiQ.js",
      "/build/chunks/tooltip-Dh-GCyoz.js",
      "/build/chunks/correctAssetUrl-8jt7Bzg0.js",
      "/build/chunks/file-sharing-provider-NtsXpuMT.js",
      "/build/chunks/sentry-DCGaZcF5.js",
      "/build/chunks/button-CB2fQLpx.js",
      "/build/chunks/index-5zs3RZdd.js",
      "/build/chunks/env-context-DebTkedx.js",
      "/build/chunks/form-validation-BmVkRcjs.js",
      "/build/chunks/StripeModal-D_zJSTg3.js",
      "/build/chunks/error-CNFYeXfL.js",
      "/build/chunks/forward-platform-action-cZbimJfK.js",
      "/build/chunks/runtime-a9fv597q.js",
      "/build/chunks/toggle-group-BSQQLJtK.js",
      "/build/chunks/focus-visible-outline-CA5WDHp1.js",
      "/build/chunks/footer-BhUrYW9s.js",
      "/build/chunks/link-button-Dgv_yPAf.js",
      "/build/chunks/plus-icon-BzkK1_R0.js",
      "/build/chunks/arrow-right-icon-CJx94PN2.js",
      "/build/chunks/navigation-tabs-BJf4kUpl.js",
      "/build/chunks/use-callback-ref-CJ9SODNh.js",
      "/build/chunks/alert-Bsob527P.js",
      "/build/chunks/base-button-BOVQiXV3.js",
      "/build/chunks/use-state-ref-0aYGV7fB.js",
      "/build/chunks/result-BtcenhOc.js",
      "/build/chunks/gtm-CBAuTBQe.js",
      "/build/chunks/get-api-DWzc_bBF.js",
      "/build/chunks/use-controlled-state-6BKWRsRt.js",
      "/build/chunks/resolve-to-node-Bl44lgnH.js",
      "/build/chunks/runtime-2_b2CLRu.js",
      "/build/chunks/VerificationStatusEnum-BMWjV5ER.js",
      "/build/chunks/AccountSubscriptionTier-Cz37hh3K.js",
      "/build/chunks/UsStateCodeAlpha2-sRkxuwjy.js",
      "/build/chunks/form-schema-utils-CKHKKg7G.js",
      "/build/chunks/types-CeqL-daw.js",
      "/build/chunks/modal-content-window-title-header-DByhHMtf.js",
      "/build/chunks/noop-BjFrJKj1.js",
      "/build/chunks/preload-helper-ckwbz45p.js",
      "/build/chunks/create-lazy-singleton-cLopSc4o.js",
      "/build/chunks/use-self-cancel-timeout-DCHuMrr-.js",
      "/build/chunks/use-self-cancel-interval-BgB7hfvd.js",
      "/build/chunks/createFormData-6W1bV2BK.js",
      "/build/chunks/get-sharing-bucket-expiration-label-BxASTJP2.js",
      "/build/chunks/auth-form-BNw1-pAv.js",
      "/build/chunks/use-typed-explicit-fetcher-fhEyK6eX.js",
      "/build/chunks/authenticity-token-CFgl6Z4h.js",
      "/build/chunks/auth-form-validation-C7l7Lp9m.js",
      "/build/chunks/use-const-CyuDI2Jw.js",
      "/build/chunks/auth-context-DVtKf2vI.js",
      "/build/chunks/navigation-link-De5ItD8a.js",
      "/build/chunks/app-integration-provider-4-SaOz_c.js",
      "/build/chunks/app-integration-loading-D3uWt4C6.js",
      "/build/chunks/client-only-CnbT09nL.js",
      "/build/chunks/auth-window-messenger-DvswJzyt.js",
      "/build/chunks/use-external-wallet-dcgxeJzM.js",
      "/build/chunks/divider-Bx5FVaq5.js",
      "/build/chunks/user-context-H9i7VnPA.js",
      "/build/chunks/CryptoCurrency-C8i-2yC7.js",
      "/build/chunks/format-crypto-currency-DU9teVm2.js",
      "/build/chunks/index-CWrIKnBx.js",
      "/build/chunks/file-name-D6aW1GMb.js",
      "/build/chunks/content-item-name-BgJnKYk_.js",
      "/build/chunks/feedback-tooltip-DnQoTtgx.js",
      "/build/chunks/dropdown-menu-item-Db0oH43Q.js",
      "/build/chunks/CompositeItem-C2QJYDDY.js",
      "/build/chunks/file-descriptor-CGrQeZua.js",
      "/build/chunks/format-1NPDPTzm.js",
      "/build/chunks/shared-DwIwScEe.js",
      "/build/chunks/use-copyright-Dc7D5n5M.js",
      "/build/chunks/tab-button-Ds5-Xr2w.js"
    ],
    "css": []
  },
  "routes": {
    "root": {
      "id": "root",
      "path": "",
      "hasAction": false,
      "hasLoader": false,
      "hasClientAction": false,
      "hasClientLoader": false,
      "hasClientMiddleware": false,
      "hasDefaultExport": true,
      "hasErrorBoundary": true,
      "module": "/build/chunks/entry/root-Y8iUtRpO.js",
      "imports": [
        "/build/chunks/jsx-runtime-D_zvdyIk.js",
        "/build/chunks/chunk-4N6VE7H7-CYH4PXiQ.js",
        "/build/chunks/tooltip-Dh-GCyoz.js",
        "/build/chunks/correctAssetUrl-8jt7Bzg0.js",
        "/build/chunks/file-sharing-provider-NtsXpuMT.js",
        "/build/chunks/sentry-DCGaZcF5.js",
        "/build/chunks/button-CB2fQLpx.js",
        "/build/chunks/index-5zs3RZdd.js",
        "/build/chunks/env-context-DebTkedx.js",
        "/build/chunks/form-validation-BmVkRcjs.js",
        "/build/chunks/StripeModal-D_zJSTg3.js",
        "/build/chunks/error-CNFYeXfL.js",
        "/build/chunks/forward-platform-action-cZbimJfK.js",
        "/build/chunks/runtime-a9fv597q.js",
        "/build/chunks/toggle-group-BSQQLJtK.js",
        "/build/chunks/focus-visible-outline-CA5WDHp1.js",
        "/build/chunks/footer-BhUrYW9s.js",
        "/build/chunks/link-button-Dgv_yPAf.js",
        "/build/chunks/plus-icon-BzkK1_R0.js",
        "/build/chunks/arrow-right-icon-CJx94PN2.js",
        "/build/chunks/navigation-tabs-BJf4kUpl.js",
        "/build/chunks/use-callback-ref-CJ9SODNh.js",
        "/build/chunks/alert-Bsob527P.js",
        "/build/chunks/base-button-BOVQiXV3.js",
        "/build/chunks/use-state-ref-0aYGV7fB.js",
        "/build/chunks/result-BtcenhOc.js",
        "/build/chunks/gtm-CBAuTBQe.js",
        "/build/chunks/get-api-DWzc_bBF.js",
        "/build/chunks/use-controlled-state-6BKWRsRt.js",
        "/build/chunks/resolve-to-node-Bl44lgnH.js",
        "/build/chunks/runtime-2_b2CLRu.js",
        "/build/chunks/VerificationStatusEnum-BMWjV5ER.js",
        "/build/chunks/AccountSubscriptionTier-Cz37hh3K.js",
        "/build/chunks/UsStateCodeAlpha2-sRkxuwjy.js",
        "/build/chunks/form-schema-utils-CKHKKg7G.js",
        "/build/chunks/types-CeqL-daw.js",
        "/build/chunks/modal-content-window-title-header-DByhHMtf.js",
        "/build/chunks/noop-BjFrJKj1.js",
        "/build/chunks/preload-helper-ckwbz45p.js",
        "/build/chunks/create-lazy-singleton-cLopSc4o.js",
        "/build/chunks/use-self-cancel-timeout-DCHuMrr-.js",
        "/build/chunks/use-self-cancel-interval-BgB7hfvd.js",
        "/build/chunks/createFormData-6W1bV2BK.js",
        "/build/chunks/get-sharing-bucket-expiration-label-BxASTJP2.js",
        "/build/chunks/auth-form-BNw1-pAv.js",
        "/build/chunks/use-typed-explicit-fetcher-fhEyK6eX.js",
        "/build/chunks/authenticity-token-CFgl6Z4h.js",
        "/build/chunks/auth-form-validation-C7l7Lp9m.js",
        "/build/chunks/use-const-CyuDI2Jw.js",
        "/build/chunks/auth-context-DVtKf2vI.js",
        "/build/chunks/navigation-link-De5ItD8a.js",
        "/build/chunks/app-integration-provider-4-SaOz_c.js",
        "/build/chunks/app-integration-loading-D3uWt4C6.js",
        "/build/chunks/client-only-CnbT09nL.js",
        "/build/chunks/auth-window-messenger-DvswJzyt.js",
        "/build/chunks/use-external-wallet-dcgxeJzM.js",
        "/build/chunks/divider-Bx5FVaq5.js",
        "/build/chunks/user-context-H9i7VnPA.js",
        "/build/chunks/CryptoCurrency-C8i-2yC7.js",
        "/build/chunks/format-crypto-currency-DU9teVm2.js",
        "/build/chunks/index-CWrIKnBx.js",
        "/build/chunks/file-name-D6aW1GMb.js",
        "/build/chunks/content-item-name-BgJnKYk_.js",
        "/build/chunks/feedback-tooltip-DnQoTtgx.js",
        "/build/chunks/dropdown-menu-item-Db0oH43Q.js",
        "/build/chunks/CompositeItem-C2QJYDDY.js",
        "/build/chunks/file-descriptor-CGrQeZua.js",
        "/build/chunks/format-1NPDPTzm.js",
        "/build/chunks/shared-DwIwScEe.js",
        "/build/chunks/use-copyright-Dc7D5n5M.js",
        "/build/chunks/tab-button-Ds5-Xr2w.js",
        "/build/chunks/use-sentry-capture-route-error-DQjqgE2j.js",
        "/build/chunks/root-data-from-meta-_uWRppwb.js",
        "/build/chunks/mgid-BClyNFEN.js",
        "/build/chunks/page-error-content-beLpRn94.js",
        "/build/chunks/default-shell-layout-GstI-jbb.js",
        "/build/chunks/api-context-7msjQt-g.js",
        "/build/chunks/creator-name-CiLx5-S8.js",
        "/build/chunks/asset-aspect-ratio-CFxZTYNK.js",
        "/build/chunks/limewire-logo-Dqzw9EF0.js",
        "/build/chunks/use-logout-DTFjcmcZ.js",
        "/build/chunks/creator-834ASwQB.js",
        "/build/chunks/errors-Bt-IsbGS.js"
      ],
      "css": []
    },
    "routes/__root": {
      "id": "routes/__root",
      "parentId": "root",
      "hasAction": false,
      "hasLoader": true,
      "hasClientAction": false,
      "hasClientLoader": false,
      "hasClientMiddleware": false,
      "hasDefaultExport": true,
      "hasErrorBoundary": true,
      "module": "/build/chunks/entry/__root-4OwC_upI.js",
      "imports": [
        "/build/chunks/chunk-4N6VE7H7-CYH4PXiQ.js",
        "/build/chunks/jsx-runtime-D_zvdyIk.js",
        "/build/chunks/authenticity-token-CFgl6Z4h.js",
        "/build/chunks/runtime-2_b2CLRu.js",
        "/build/chunks/AccountSubscriptionTier-Cz37hh3K.js",
        "/build/chunks/mgid-slot-DhBerfc6.js",
        "/build/chunks/default-shell-layout-GstI-jbb.js",
        "/build/chunks/env-context-DebTkedx.js",
        "/build/chunks/mgid-BClyNFEN.js",
        "/build/chunks/share-nearby-provider-CwuMIupI.js",
        "/build/chunks/auth-context-DVtKf2vI.js",
        "/build/chunks/user-context-H9i7VnPA.js",
        "/build/chunks/StripeModal-D_zJSTg3.js",
        "/build/chunks/createFormData-6W1bV2BK.js",
        "/build/chunks/sentry-DCGaZcF5.js",
        "/build/chunks/tooltip-Dh-GCyoz.js",
        "/build/chunks/file-sharing-provider-NtsXpuMT.js",
        "/build/chunks/index-5zs3RZdd.js",
        "/build/chunks/modal-content-window-title-header-DByhHMtf.js",
        "/build/chunks/file-name-D6aW1GMb.js",
        "/build/chunks/form-validation-BmVkRcjs.js",
        "/build/chunks/focus-visible-outline-CA5WDHp1.js",
        "/build/chunks/get-sharing-bucket-expiration-label-BxASTJP2.js",
        "/build/chunks/result-BtcenhOc.js",
        "/build/chunks/get-api-DWzc_bBF.js",
        "/build/chunks/preload-helper-ckwbz45p.js",
        "/build/chunks/noop-BjFrJKj1.js",
        "/build/chunks/file-descriptor-CGrQeZua.js",
        "/build/chunks/use-controlled-state-6BKWRsRt.js",
        "/build/chunks/use-callback-ref-CJ9SODNh.js",
        "/build/chunks/client-only-CnbT09nL.js",
        "/build/chunks/runtime-a9fv597q.js",
        "/build/chunks/api-context-7msjQt-g.js",
        "/build/chunks/auth-form-BNw1-pAv.js",
        "/build/chunks/use-logout-DTFjcmcZ.js",
        "/build/chunks/alert-Bsob527P.js",
        "/build/chunks/button-CB2fQLpx.js",
        "/build/chunks/script-EPnTUGRP.js",
        "/build/chunks/app-integration-provider-4-SaOz_c.js",
        "/build/chunks/use-sentry-capture-route-error-DQjqgE2j.js",
        "/build/chunks/CryptoCurrency-C8i-2yC7.js",
        "/build/chunks/format-crypto-currency-DU9teVm2.js",
        "/build/chunks/navigation-link-De5ItD8a.js",
        "/build/chunks/tab-button-Ds5-Xr2w.js",
        "/build/chunks/toggle-group-BSQQLJtK.js",
        "/build/chunks/use-state-ref-0aYGV7fB.js",
        "/build/chunks/use-const-CyuDI2Jw.js",
        "/build/chunks/resolve-to-node-Bl44lgnH.js",
        "/build/chunks/error-CNFYeXfL.js",
        "/build/chunks/create-lazy-singleton-cLopSc4o.js",
        "/build/chunks/base-button-BOVQiXV3.js",
        "/build/chunks/creator-name-CiLx5-S8.js",
        "/build/chunks/asset-aspect-ratio-CFxZTYNK.js",
        "/build/chunks/VerificationStatusEnum-BMWjV5ER.js",
        "/build/chunks/shared-DwIwScEe.js",
        "/build/chunks/limewire-logo-Dqzw9EF0.js",
        "/build/chunks/CompositeItem-C2QJYDDY.js",
        "/build/chunks/arrow-right-icon-CJx94PN2.js",
        "/build/chunks/creator-834ASwQB.js",
        "/build/chunks/use-copyright-Dc7D5n5M.js",
        "/build/chunks/copy-input-0I8Jahig.js",
        "/build/chunks/use-self-cancel-timeout-DCHuMrr-.js",
        "/build/chunks/types-CeqL-daw.js",
        "/build/chunks/index-CWrIKnBx.js",
        "/build/chunks/UsStateCodeAlpha2-sRkxuwjy.js",
        "/build/chunks/form-schema-utils-CKHKKg7G.js",
        "/build/chunks/link-button-Dgv_yPAf.js",
        "/build/chunks/use-self-cancel-interval-BgB7hfvd.js",
        "/build/chunks/use-typed-explicit-fetcher-fhEyK6eX.js",
        "/build/chunks/auth-form-validation-C7l7Lp9m.js",
        "/build/chunks/app-integration-loading-D3uWt4C6.js",
        "/build/chunks/auth-window-messenger-DvswJzyt.js",
        "/build/chunks/use-external-wallet-dcgxeJzM.js",
        "/build/chunks/divider-Bx5FVaq5.js",
        "/build/chunks/page-error-content-beLpRn94.js",
        "/build/chunks/errors-Bt-IsbGS.js"
      ],
      "css": []
    },
    "routes/__root/d/$id": {
      "id": "routes/__root/d/$id",
      "parentId": "routes/__root",
      "path": "d/:id",
      "hasAction": false,
      "hasLoader": true,
      "hasClientAction": false,
      "hasClientLoader": false,
      "hasClientMiddleware": false,
      "hasDefaultExport": true,
      "hasErrorBoundary": false,
      "module": "/build/chunks/entry/_id-C1I2UVlI.js",
      "imports": [
        "/build/chunks/chunk-4N6VE7H7-CYH4PXiQ.js",
        "/build/chunks/jsx-runtime-D_zvdyIk.js",
        "/build/chunks/shell-layout-aside-65Zf2JuP.js",
        "/build/chunks/file-sharing-provider-NtsXpuMT.js",
        "/build/chunks/page-column-layout-DWZQyDxP.js",
        "/build/chunks/get-default-seo-preview-image-19rrZO0W.js",
        "/build/chunks/page-error-content-beLpRn94.js",
        "/build/chunks/page-error-404-Ba3LfCNG.js",
        "/build/chunks/default-shell-layout-GstI-jbb.js",
        "/build/chunks/index-5zs3RZdd.js",
        "/build/chunks/get-api-DWzc_bBF.js",
        "/build/chunks/runtime-2_b2CLRu.js",
        "/build/chunks/runtime-a9fv597q.js",
        "/build/chunks/feedback-tooltip-DnQoTtgx.js",
        "/build/chunks/resolve-to-node-Bl44lgnH.js",
        "/build/chunks/alert-Bsob527P.js",
        "/build/chunks/content-item-name-BgJnKYk_.js",
        "/build/chunks/use-self-cancel-timeout-DCHuMrr-.js",
        "/build/chunks/navigation-link-De5ItD8a.js",
        "/build/chunks/shared-DwIwScEe.js",
        "/build/chunks/file-name-D6aW1GMb.js",
        "/build/chunks/form-schema-utils-CKHKKg7G.js",
        "/build/chunks/modal-content-window-title-header-DByhHMtf.js",
        "/build/chunks/form-validation-BmVkRcjs.js",
        "/build/chunks/button-CB2fQLpx.js",
        "/build/chunks/types-CeqL-daw.js",
        "/build/chunks/focus-visible-outline-CA5WDHp1.js",
        "/build/chunks/base-button-BOVQiXV3.js",
        "/build/chunks/use-controlled-state-6BKWRsRt.js",
        "/build/chunks/use-state-ref-0aYGV7fB.js",
        "/build/chunks/navigation-tabs-BJf4kUpl.js",
        "/build/chunks/mgid-slot-DhBerfc6.js",
        "/build/chunks/env-context-DebTkedx.js",
        "/build/chunks/use-callback-ref-CJ9SODNh.js",
        "/build/chunks/noop-BjFrJKj1.js",
        "/build/chunks/mgid-BClyNFEN.js",
        "/build/chunks/api-context-7msjQt-g.js",
        "/build/chunks/user-context-H9i7VnPA.js",
        "/build/chunks/creator-name-CiLx5-S8.js",
        "/build/chunks/use-const-CyuDI2Jw.js",
        "/build/chunks/get-sharing-bucket-expiration-label-BxASTJP2.js",
        "/build/chunks/format-1NPDPTzm.js",
        "/build/chunks/auth-form-BNw1-pAv.js",
        "/build/chunks/result-BtcenhOc.js",
        "/build/chunks/date-time-D44bRngG.js",
        "/build/chunks/client-only-CnbT09nL.js",
        "/build/chunks/VerificationStatusEnum-BMWjV5ER.js",
        "/build/chunks/AccountSubscriptionTier-Cz37hh3K.js",
        "/build/chunks/UsStateCodeAlpha2-sRkxuwjy.js",
        "/build/chunks/link-button-Dgv_yPAf.js",
        "/build/chunks/root-data-from-meta-_uWRppwb.js",
        "/build/chunks/CryptoCurrency-C8i-2yC7.js",
        "/build/chunks/format-crypto-currency-DU9teVm2.js",
        "/build/chunks/tab-button-Ds5-Xr2w.js",
        "/build/chunks/toggle-group-BSQQLJtK.js",
        "/build/chunks/error-CNFYeXfL.js",
        "/build/chunks/preload-helper-ckwbz45p.js",
        "/build/chunks/create-lazy-singleton-cLopSc4o.js",
        "/build/chunks/limewire-logo-Dqzw9EF0.js",
        "/build/chunks/tooltip-Dh-GCyoz.js",
        "/build/chunks/CompositeItem-C2QJYDDY.js",
        "/build/chunks/arrow-right-icon-CJx94PN2.js",
        "/build/chunks/use-logout-DTFjcmcZ.js",
        "/build/chunks/use-typed-explicit-fetcher-fhEyK6eX.js",
        "/build/chunks/creator-834ASwQB.js",
        "/build/chunks/use-copyright-Dc7D5n5M.js",
        "/build/chunks/app-integration-provider-4-SaOz_c.js",
        "/build/chunks/app-integration-loading-D3uWt4C6.js",
        "/build/chunks/use-self-cancel-interval-BgB7hfvd.js",
        "/build/chunks/createFormData-6W1bV2BK.js",
        "/build/chunks/auth-context-DVtKf2vI.js",
        "/build/chunks/asset-aspect-ratio-CFxZTYNK.js",
        "/build/chunks/index-CWrIKnBx.js",
        "/build/chunks/authenticity-token-CFgl6Z4h.js",
        "/build/chunks/auth-form-validation-C7l7Lp9m.js",
        "/build/chunks/auth-window-messenger-DvswJzyt.js",
        "/build/chunks/use-external-wallet-dcgxeJzM.js",
        "/build/chunks/divider-Bx5FVaq5.js"
      ],
      "css": []
    },
    "routes/__root/__landing": {
      "id": "routes/__root/__landing",
      "parentId": "routes/__root",
      "hasAction": false,
      "hasLoader": true,
      "hasClientAction": false,
      "hasClientLoader": false,
      "hasClientMiddleware": false,
      "hasDefaultExport": true,
      "hasErrorBoundary": false,
      "module": "/build/chunks/entry/__landing-Cahq9YEn.js",
      "imports": [
        "/build/chunks/__landing-wPXq_Oql.js",
        "/build/chunks/chunk-4N6VE7H7-CYH4PXiQ.js",
        "/build/chunks/jsx-runtime-D_zvdyIk.js",
        "/build/chunks/forward-platform-action-cZbimJfK.js",
        "/build/chunks/index-5zs3RZdd.js",
        "/build/chunks/link-button-Dgv_yPAf.js",
        "/build/chunks/base-button-BOVQiXV3.js",
        "/build/chunks/focus-visible-outline-CA5WDHp1.js",
        "/build/chunks/runtime-a9fv597q.js",
        "/build/chunks/get-sharing-bucket-expiration-label-BxASTJP2.js",
        "/build/chunks/auth-form-BNw1-pAv.js",
        "/build/chunks/file-sharing-provider-NtsXpuMT.js",
        "/build/chunks/get-api-DWzc_bBF.js",
        "/build/chunks/runtime-2_b2CLRu.js",
        "/build/chunks/result-BtcenhOc.js",
        "/build/chunks/VerificationStatusEnum-BMWjV5ER.js",
        "/build/chunks/AccountSubscriptionTier-Cz37hh3K.js",
        "/build/chunks/UsStateCodeAlpha2-sRkxuwjy.js",
        "/build/chunks/form-schema-utils-CKHKKg7G.js",
        "/build/chunks/types-CeqL-daw.js",
        "/build/chunks/use-state-ref-0aYGV7fB.js",
        "/build/chunks/use-callback-ref-CJ9SODNh.js",
        "/build/chunks/use-const-CyuDI2Jw.js",
        "/build/chunks/modal-content-window-title-header-DByhHMtf.js",
        "/build/chunks/use-controlled-state-6BKWRsRt.js",
        "/build/chunks/resolve-to-node-Bl44lgnH.js",
        "/build/chunks/noop-BjFrJKj1.js",
        "/build/chunks/tooltip-Dh-GCyoz.js",
        "/build/chunks/form-validation-BmVkRcjs.js",
        "/build/chunks/alert-Bsob527P.js",
        "/build/chunks/use-self-cancel-timeout-DCHuMrr-.js",
        "/build/chunks/use-self-cancel-interval-BgB7hfvd.js",
        "/build/chunks/toggle-group-BSQQLJtK.js",
        "/build/chunks/createFormData-6W1bV2BK.js",
        "/build/chunks/button-CB2fQLpx.js",
        "/build/chunks/env-context-DebTkedx.js",
        "/build/chunks/use-typed-explicit-fetcher-fhEyK6eX.js",
        "/build/chunks/authenticity-token-CFgl6Z4h.js",
        "/build/chunks/auth-form-validation-C7l7Lp9m.js",
        "/build/chunks/auth-context-DVtKf2vI.js",
        "/build/chunks/navigation-link-De5ItD8a.js",
        "/build/chunks/app-integration-provider-4-SaOz_c.js",
        "/build/chunks/app-integration-loading-D3uWt4C6.js",
        "/build/chunks/client-only-CnbT09nL.js",
        "/build/chunks/auth-window-messenger-DvswJzyt.js",
        "/build/chunks/use-external-wallet-dcgxeJzM.js",
        "/build/chunks/preload-helper-ckwbz45p.js",
        "/build/chunks/create-lazy-singleton-cLopSc4o.js",
        "/build/chunks/divider-Bx5FVaq5.js",
        "/build/chunks/CryptoCurrency-C8i-2yC7.js",
        "/build/chunks/file-name-D6aW1GMb.js",
        "/build/chunks/content-item-name-BgJnKYk_.js",
        "/build/chunks/arrow-right-icon-CJx94PN2.js",
        "/build/chunks/feedback-tooltip-DnQoTtgx.js",
        "/build/chunks/dropdown-menu-item-Db0oH43Q.js",
        "/build/chunks/CompositeItem-C2QJYDDY.js",
        "/build/chunks/file-descriptor-CGrQeZua.js",
        "/build/chunks/format-1NPDPTzm.js",
        "/build/chunks/index-CWrIKnBx.js",
        "/build/chunks/StripeModal-D_zJSTg3.js",
        "/build/chunks/user-context-H9i7VnPA.js",
        "/build/chunks/format-crypto-currency-DU9teVm2.js",
        "/build/chunks/error-CNFYeXfL.js",
        "/build/chunks/shell-layout-aside-65Zf2JuP.js",
        "/build/chunks/mgid-slot-DhBerfc6.js",
        "/build/chunks/mgid-BClyNFEN.js",
        "/build/chunks/date-time-D44bRngG.js",
        "/build/chunks/default-shell-layout-GstI-jbb.js",
        "/build/chunks/tab-button-Ds5-Xr2w.js",
        "/build/chunks/api-context-7msjQt-g.js",
        "/build/chunks/creator-name-CiLx5-S8.js",
        "/build/chunks/asset-aspect-ratio-CFxZTYNK.js",
        "/build/chunks/shared-DwIwScEe.js",
        "/build/chunks/limewire-logo-Dqzw9EF0.js",
        "/build/chunks/use-logout-DTFjcmcZ.js",
        "/build/chunks/creator-834ASwQB.js",
        "/build/chunks/use-copyright-Dc7D5n5M.js",
        "/build/chunks/navigation-tabs-BJf4kUpl.js",
        "/build/chunks/share-nearby-provider-CwuMIupI.js",
        "/build/chunks/copy-input-0I8Jahig.js",
        "/build/chunks/script-EPnTUGRP.js",
        "/build/chunks/page-column-layout-DWZQyDxP.js"
      ],
      "css": []
    },
    "routes/__root/__landing/index": {
      "id": "routes/__root/__landing/index",
      "parentId": "routes/__root/__landing",
      "index": true,
      "hasAction": false,
      "hasLoader": true,
      "hasClientAction": false,
      "hasClientLoader": false,
      "hasClientMiddleware": false,
      "hasDefaultExport": true,
      "hasErrorBoundary": false,
      "module": "/build/chunks/entry/index-DOPVeHiG.js",
      "imports": [
        "/build/chunks/chunk-4N6VE7H7-CYH4PXiQ.js",
        "/build/chunks/get-default-seo-preview-image-19rrZO0W.js",
        "/build/chunks/root-data-from-meta-_uWRppwb.js"
      ],
      "css": []
    }
  },
  "url": "/build/assets/manifest-06151e2d.js",
  "version": "06151e2d"
};
  window.__reactRouterRouteModules = {"root":route0,"routes/__root":route1,"routes/__root/d/$id":route2};

import("/build/chunks/entry/entry.client-h-8J_f_U.js");</script><script>((storageKey2, restoreKey) => {
    if (!window.history.state || !window.history.state.key) {
      let key = Math.random().toString(32).slice(2);
      window.history.replaceState({ key }, "");
    }
    try {
      let positions = JSON.parse(sessionStorage.getItem(storageKey2) || "{}");
      let storedY = positions[restoreKey || window.history.state.key];
      if (typeof storedY === "number") {
        window.scrollTo(0, storedY);
      }
    } catch (error) {
      console.error(error);
      sessionStorage.removeItem(storageKey2);
    }
  })("react-router-scroll-positions", null)</script><!--$--><script>window.__reactRouterContext.streamController.enqueue("[{\"_1\":2,\"_3\":-5,\"_4\":-5},\"loaderData\",{\"_5\":6,\"_7\":8},\"actionData\",\"errors\",\"routes/__root\",{\"_106\":-7,\"_107\":-5,\"_108\":-7,\"_109\":110,\"_111\":112,\"_113\":-7,\"_114\":-7,\"_115\":-5,\"_116\":36,\"_117\":-7,\"_118\":-7,\"_119\":120,\"_121\":-7,\"_122\":-5},\"routes/__root/d/$id\",{\"_9\":10,\"_11\":12},\"sharingId\",\"xZTrn\",\"sharingBucketContentData\",{\"_13\":14,\"_15\":16},\"ok\",true,\"value\",{\"_17\":18,\"_19\":20,\"_21\":22,\"_23\":14},\"sharingBucket\",{\"_25\":55,\"_82\":-7,\"_83\":84,\"_85\":86,\"_87\":88,\"_89\":90,\"_9\":10,\"_91\":26,\"_92\":93,\"_94\":63,\"_95\":96,\"_37\":97,\"_39\":98,\"_35\":36,\"_99\":100,\"_101\":102,\"_103\":102,\"_104\":36},\"contentItemList\",[52],\"fileEncryptionKeys\",[24],\"displayAds\",{\"_25\":26,\"_27\":28,\"_29\":30,\"_31\":32,\"_33\":34,\"_35\":36,\"_37\":38,\"_39\":40},\"id\",\"59a73252-2d47-4ffb-9041-c6b72cce5bda\",\"publicKey\",\"BFZt6Sm5WJOKE7I5PrTQFSv/fKNtPG80oufRdCv4+VuqpSqoZI86FJfmRwYkxStF8rG50UqypXPajOZElEdmtJ0=\",\"privateKeys\",[45],\"encryptedPassphrase\",\"b+KmrcTl4Y0qt2EsdrgwSc/rne7tSRyTReU=\",\"passphraseWrappedPrivateKey\",\"S8pOuFyarpB+Q5AIdqQiFiTkn0VJEMJujZelGdNVyA7ljXK7zaSfwA==\",\"deleted\",false,\"createdDate\",[\"D\",1790300040550],\"lastModifiedTimestamp\",{\"_41\":42,\"_43\":44},\"time\",1790300143,\"increment\",31,{\"_46\":47,\"_48\":49,\"_50\":51},\"encryptedPrivateKey\",\"xtgFMPVabkfvz5jPn6aROhXeoG+WfxXsR6GHwDJBQx6WXT62SR9Clg==\",\"encryptedByKeyType\",\"USER_ENCRYPTION_KEY\",\"encryptedByKeyId\",\"47e02f1d-0534-446e-8462-61ac338a95fb\",{\"_25\":53,\"_54\":55,\"_56\":57,\"_58\":59,\"_60\":61,\"_62\":63,\"_64\":65,\"_66\":67,\"_68\":26,\"_69\":70,\"_71\":72,\"_73\":74,\"_75\":-7,\"_37\":76,\"_39\":77,\"_35\":36},\"7178c8ae-0dbc-4885-aacc-a0378d655b78\",\"originalSharingBucketId\",\"c0d18472-973b-4d36-a349-554fa069c4a0\",\"s3Status\",\"UPLOADED\",\"itemType\",\"OTHER\",\"mediaType\",\"text/typescript\",\"size\",20298,\"nameEncrypted\",\"ZGcEueOYJ0/hO537BbMC027GZ5guqSIBBlLkTbtflQI=\",\"sha1Encrypted\",\"RL6axqh3dyQikXLKCVPpbZWOhzqJWi6Qq/ut4Zri0CKZLtGB\",\"baseFileEncryptionKeyId\",\"ephemeralPublicKey\",\"BMGVm94H3fyJlcPVPcBSH2/zH3iBf0Q94v/rXm0IH4aO0WFIXAHmbmhMERTlRbqj6kwgkghp0mOfPhP2ZPY9EiM=\",\"metadata\",{\"_80\":81},\"previews\",[],\"nsfw\",[\"D\",1790300041870],{\"_41\":78,\"_43\":79},1790300126,10,\"metadataType\",\"unknown\",\"ownerId\",\"clientDeviceId\",\"7fc6509e-7e77-43f8-850c-4726e3166bde\",\"ownerNick\",\"anonymous\",\"sharingStatus\",\"SHARED\",\"sharingPermission\",\"VIEWER\",\"primaryEncryptionKeyId\",\"contentItemIds\",[53],\"totalFileSize\",\"name\",\"CyberNetwork.tsx\",[\"D\",1790300041869],{\"_41\":42,\"_43\":105},\"expiresAt\",[\"D\",1790559241869],\"downloadCounter\",0,\"publicDownloadCounter\",\"pinned\",29,\"promotionBanner\",\"platformBanner\",\"cacheId\",\"env\",{\"_129\":130,\"_131\":132,\"_133\":36,\"_134\":36,\"_135\":136,\"_137\":132,\"_138\":139,\"_140\":141,\"_142\":143,\"_144\":145,\"_146\":147,\"_148\":149,\"_150\":151,\"_152\":153},\"csrfToken\",\"TR_X2guXfQlQGzc3xxE1JH2AJzp8OeiQKnSo05YxkMv4Aaq_dIhFwdAKpHJi4xGkzyBaGXvzmiiVAgeOV0UAXQ\",\"selfClientId\",\"selfCsrf\",\"referrer\",\"isAuthenticated\",\"self\",\"lmwrBalance\",\"lmwrExchangeRates\",{\"_123\":124,\"_125\":126,\"_127\":128},\"aiCredits\",\"appIntegration\",\"currency\",\"LMWR\",\"exchangeRate\",0.010255949684859452,\"percentageChange24h\",-2.97336509,\"NOW\",[\"D\",1790300663554],\"CLIENT_BASE_URL\",\"https://limewire.com\",\"IS_DEV\",\"IS_STAGING\",\"API_BASE_URL\",\"https://api.limewire.com\",\"CANONICAL_BASE_URL\",\"LIMEWIRE_FREE_USER_ID\",\"7f219511-0a09-403c-a94b-caa56419b5f8\",\"LIMEWIRE_PRO_USER_ID\",\"1e2c66a9-7073-499b-86fb-b134a088ce44\",\"SENTRY_DSN\",\"https://3914d239cc544007a8bc3b33c2e276e7:375389f9b8fc4a58aac7ddf053335cd6@o4505008135340032.ingest.sentry.io/4505114707099648\",\"SENTRY_ENVIRONMENT\",\"production\",\"SENTRY_PROJECT\",\"limewire-js-remix\",\"GIT_RELEASE\",\"f85f0ca344014a7d746fa6a78746a729ef7e2e8f\",\"STORYBLOCK_SPACE_ACCESS_TOKEN\",\"jmGRmWycHD5MvliLQXFkXAtt\",\"TURNSTILE_SITEKEY\",\"0x4AAAAAAEVmA3xwky6ar3WJ\"]\n");</script><!--$--><script>window.__reactRouterContext.streamController.close();</script><!--/$--><!--/$--></body></html>